### ISSUE TITLE
Zmiana scrum mastera

### ISSUE THREAD

**Issue by Zofija** [Zofija/Wikipedia#1]
Z dniem 12.05.2016 zakończyłam swoją pracę jako scrum master.
Cała dokumentacja naszej pracy (wszystkie raporty) znajdują się na Trello, natomiast wszystko co udało nam się stworzyć zgodnie z celami sprintu znajduje się repozytorium "Wikipedia".
Zespół teraz powinien wybrać nową osobę do tej roli.

**Comment by kamilmachon** [comment]
Przejmę po Zosi rolę scrummastera :P Przypominam o przydzieleniu sobie
zadań na trello.

W dniu 16 maja 2016 21:32 użytkownik Zofija notifications@github.com
napisał:
